name: Monitor COSING Annexes

# 1) Dale permiso de escritura a los contenidos
permissions:
  contents: write

on:
  schedule:
    - cron:  '0 9 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      # 2) Haz checkout persistiendo credenciales (para poder push)
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 PyGithub openpyxl xlrd pandas pyexcel pyexcel-xls pyexcel-xlsx msoffcrypto-tool

      - name: Run monitor script
        env:
          # este token ya viene inyectado automáticamente
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/check_annexes.py

      - name: Commit & Push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "🔄 Auto-update COSING Anexos"
            git push
          else
            echo "🤖 No hay cambios."
          fi
